version: '3'

services:
  db:
    image: postgis/postgis:17-3.5
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"

volumes:
  dbdata:

